# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a69b4398b48f62fd427d521ebee52d9612fd0bdf39d61cc4855b4fd88113b3adec8227ed6637d77a2d5613beb77fca5304bb377bf230a0634157a39659438296

test:
  secret_key_base: 29cd823ecb5d3ca94d8516c0e1095aa7560473468d5359d93e20e75d75c1f638be121748d573095ce616b0c963f447bd8c9f1a0d38770cbbc84337ec1ee6e5c9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
